### ISSUE TITLE
Wrong classpath in README

### ISSUE THREAD

**Issue by Srogozins** [quux00/hive-json-schema#6]
In readme there are execution examples e.g.:
`java -cp target/json-hive-schema-1.0.jar net.thorndev.JsonHiveSchema file.json`

This won't work, because correct classpath is `net.thornydev.JsonHiveSchema file.json`
Likely a 'y' as omitted by a typo.

So, the correct examples should be like
`java -cp target/json-hive-schema-1.0.jar net.thornydev.JsonHiveSchema file.json`

**Comment by quux00** [comment]
Good catch - thanks very much.  Fixed now.
